# This file is part of ssh2-python.
# Copyright (C) 2017-2022 Panos Kittenis and contributors.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation, version 2.1.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
version: 2

jobs:
  linux-wheels:
    working_directory: ~/linux-wheels
    docker:
      - image: cimg/python:3.9
    environment:
      CIBW_ARCHS_LINUX: "s390x ppc64le"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup QEMU emulators
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install ppc64le,s390x
      - run:
          name: Build the Linux wheels.
          command: |
            pip3 install --user cibuildwheel==2.12.0
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

  linux-aarch64-wheels:
    working_directory: ~/linux-aarch64-wheels
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: arm.medium
    environment:
      CIBW_ARCHS_LINUX: "s390x ppc64le"
    steps:
      - checkout
      - run:
          name: Setup QEMU emulators
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install ppc64le,s390x
      - run:
          name: Build the Linux aarch64 wheels.
          command: |
            python3 -m pip install --user cibuildwheel==2.12.0
            python3 -m cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

  osx-wheels:
    working_directory: ~/osx-wheels
    macos:
      xcode: 12.5.1
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      SYSTEM_LIBSSH2: 1
    steps:
      - checkout
      - run:
          name: Build the OS X wheels.
          command: |
            pip3 install cibuildwheel==2.12.0
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

workflows:
  version: 2
  all-tests:
    jobs:
      #- linux-wheels
      - linux-aarch64-wheels
      #- osx-wheels